import type { CalendarEvent } from "@/lib/types"

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "NEET Mock Test 3",
    type: "test",
    date: "2024-12-15",
    time: "10:00",
    subject: "All Subjects",
    description: "Full length mock test covering all subjects",
    userId: "1",
  },
  {
    id: "2",
    title: "Physics Study Session",
    type: "study",
    date: "2024-12-12",
    time: "14:00",
    subject: "Physics",
    description: "Focus on Thermodynamics and Modern Physics",
    userId: "1",
  },
  {
    id: "3",
    title: "Chemistry Revision",
    type: "revision",
    date: "2024-12-13",
    time: "16:00",
    subject: "Chemistry",
    description: "Organic Chemistry reactions revision",
    userId: "1",
  },
  {
    id: "4",
    title: "Math Practice",
    type: "study",
    date: "2024-12-14",
    time: "09:00",
    subject: "Mathematics",
    description: "Calculus problems practice",
    userId: "1",
  },
  {
    id: "5",
    title: "Biology Sectional Test",
    type: "test",
    date: "2024-12-16",
    time: "11:00",
    subject: "Biology",
    description: "Genetics and Cell Biology test",
    userId: "1",
  },
  {
    id: "6",
    title: "Physics Revision",
    type: "revision",
    date: "2024-12-17",
    time: "15:00",
    subject: "Physics",
    description: "Mechanics formulas revision",
    userId: "1",
  },
]
