import type { Subject } from "@/lib/types"

export const mockSubjects: Subject[] = [
  {
    id: "1",
    name: "Physics",
    color: "#3b82f6",
    icon: "atom",
    totalTopics: 25,
    completedTopics: 18,
    averageScore: 78,
    tests: 12,
    userId: "1",
  },
  {
    id: "2",
    name: "Chemistry",
    color: "#10b981",
    icon: "flask",
    totalTopics: 22,
    completedTopics: 15,
    averageScore: 82,
    tests: 10,
    userId: "1",
  },
  {
    id: "3",
    name: "Biology",
    color: "#f59e0b",
    icon: "dna",
    totalTopics: 28,
    completedTopics: 20,
    averageScore: 85,
    tests: 14,
    userId: "1",
  },
  {
    id: "4",
    name: "Mathematics",
    color: "#ef4444",
    icon: "calculator",
    totalTopics: 30,
    completedTopics: 22,
    averageScore: 75,
    tests: 15,
    userId: "1",
  },
  {
    id: "5",
    name: "History",
    color: "#8b5cf6",
    icon: "book",
    totalTopics: 20,
    completedTopics: 12,
    averageScore: 70,
    tests: 8,
    userId: "1",
  },
]
