import type { Test } from "@/lib/types"

export const mockTests: Test[] = [
  {
    id: "1",
    name: "NEET Mock Test 1",
    subjectId: "1",
    subject: "Physics",
    category: "mock",
    score: 85,
    totalMarks: 100,
    percentage: 85,
    date: "2024-12-01",
    duration: 60,
    userId: "1",
  },
  {
    id: "2",
    name: "JEE Practice Set",
    subjectId: "4",
    subject: "Mathematics",
    category: "practice",
    score: 72,
    totalMarks: 100,
    percentage: 72,
    date: "2024-12-03",
    duration: 90,
    userId: "1",
  },
  {
    id: "3",
    name: "Chemistry Full Test",
    subjectId: "2",
    subject: "Chemistry",
    category: "full",
    score: 88,
    totalMarks: 100,
    percentage: 88,
    date: "2024-12-05",
    duration: 180,
    userId: "1",
  },
  {
    id: "4",
    name: "Biology Sectional",
    subjectId: "3",
    subject: "Biology",
    category: "sectional",
    score: 92,
    totalMarks: 100,
    percentage: 92,
    date: "2024-12-07",
    duration: 45,
    userId: "1",
  },
  {
    id: "5",
    name: "Physics Practice",
    subjectId: "1",
    subject: "Physics",
    category: "practice",
    score: 76,
    totalMarks: 100,
    percentage: 76,
    date: "2024-12-08",
    duration: 60,
    userId: "1",
  },
  {
    id: "6",
    name: "Math Sectional - Calculus",
    subjectId: "4",
    subject: "Mathematics",
    category: "sectional",
    score: 68,
    totalMarks: 100,
    percentage: 68,
    date: "2024-12-09",
    duration: 45,
    userId: "1",
  },
  {
    id: "7",
    name: "NEET Mock Test 2",
    subjectId: "3",
    subject: "Biology",
    category: "mock",
    score: 89,
    totalMarks: 100,
    percentage: 89,
    date: "2024-12-10",
    duration: 60,
    userId: "1",
  },
  {
    id: "8",
    name: "Chemistry Practice",
    subjectId: "2",
    subject: "Chemistry",
    category: "practice",
    score: 81,
    totalMarks: 100,
    percentage: 81,
    date: "2024-11-28",
    duration: 60,
    userId: "1",
  },
  {
    id: "9",
    name: "Physics Full Test",
    subjectId: "1",
    subject: "Physics",
    category: "full",
    score: 79,
    totalMarks: 100,
    percentage: 79,
    date: "2024-11-25",
    duration: 180,
    userId: "1",
  },
  {
    id: "10",
    name: "History Practice",
    subjectId: "5",
    subject: "History",
    category: "practice",
    score: 65,
    totalMarks: 100,
    percentage: 65,
    date: "2024-11-20",
    duration: 60,
    userId: "1",
  },
]
