import type { Topic } from "@/lib/types"

export const mockTopics: Topic[] = [
  // Physics topics
  {
    id: "1",
    subjectId: "1",
    name: "Mechanics",
    difficulty: "medium",
    progress: 85,
    lastStudied: "2024-12-10",
    userId: "1",
  },
  {
    id: "2",
    subjectId: "1",
    name: "Thermodynamics",
    difficulty: "hard",
    progress: 60,
    lastStudied: "2024-12-08",
    userId: "1",
  },
  {
    id: "3",
    subjectId: "1",
    name: "Optics",
    difficulty: "medium",
    progress: 75,
    lastStudied: "2024-12-05",
    userId: "1",
  },
  {
    id: "4",
    subjectId: "1",
    name: "Electromagnetism",
    difficulty: "hard",
    progress: 55,
    lastStudied: "2024-12-03",
    userId: "1",
  },
  { id: "5", subjectId: "1", name: "Modern Physics", difficulty: "hard", progress: 40, userId: "1" },

  // Chemistry topics
  {
    id: "6",
    subjectId: "2",
    name: "Organic Chemistry",
    difficulty: "hard",
    progress: 70,
    lastStudied: "2024-12-09",
    userId: "1",
  },
  {
    id: "7",
    subjectId: "2",
    name: "Inorganic Chemistry",
    difficulty: "medium",
    progress: 80,
    lastStudied: "2024-12-07",
    userId: "1",
  },
  {
    id: "8",
    subjectId: "2",
    name: "Physical Chemistry",
    difficulty: "hard",
    progress: 65,
    lastStudied: "2024-12-04",
    userId: "1",
  },
  { id: "9", subjectId: "2", name: "Electrochemistry", difficulty: "medium", progress: 72, userId: "1" },

  // Biology topics
  {
    id: "10",
    subjectId: "3",
    name: "Cell Biology",
    difficulty: "easy",
    progress: 95,
    lastStudied: "2024-12-10",
    userId: "1",
  },
  {
    id: "11",
    subjectId: "3",
    name: "Genetics",
    difficulty: "medium",
    progress: 85,
    lastStudied: "2024-12-08",
    userId: "1",
  },
  {
    id: "12",
    subjectId: "3",
    name: "Human Physiology",
    difficulty: "medium",
    progress: 78,
    lastStudied: "2024-12-06",
    userId: "1",
  },
  { id: "13", subjectId: "3", name: "Ecology", difficulty: "easy", progress: 88, userId: "1" },
  { id: "14", subjectId: "3", name: "Plant Biology", difficulty: "medium", progress: 70, userId: "1" },

  // Mathematics topics
  {
    id: "15",
    subjectId: "4",
    name: "Calculus",
    difficulty: "hard",
    progress: 80,
    lastStudied: "2024-12-09",
    userId: "1",
  },
  {
    id: "16",
    subjectId: "4",
    name: "Algebra",
    difficulty: "medium",
    progress: 90,
    lastStudied: "2024-12-07",
    userId: "1",
  },
  {
    id: "17",
    subjectId: "4",
    name: "Trigonometry",
    difficulty: "medium",
    progress: 85,
    lastStudied: "2024-12-05",
    userId: "1",
  },
  { id: "18", subjectId: "4", name: "Coordinate Geometry", difficulty: "medium", progress: 75, userId: "1" },
  { id: "19", subjectId: "4", name: "Statistics", difficulty: "easy", progress: 92, userId: "1" },

  // History topics
  {
    id: "20",
    subjectId: "5",
    name: "Ancient History",
    difficulty: "medium",
    progress: 65,
    lastStudied: "2024-12-04",
    userId: "1",
  },
  { id: "21", subjectId: "5", name: "Medieval History", difficulty: "medium", progress: 58, userId: "1" },
  { id: "22", subjectId: "5", name: "Modern History", difficulty: "hard", progress: 50, userId: "1" },
]
