import type { Test, Subject, CalendarEvent, Achievement, Goal } from "./store"

export const seedTests: Test[] = [
  {
    id: "1",
    name: "NEET Mock Test 1",
    subject: "Biology",
    category: "mock",
    score: 145,
    totalMarks: 180,
    date: "2024-01-15",
    topics: ["Cell Biology", "Genetics"],
    difficulty: "medium",
    timeSpent: 180,
  },
  {
    id: "2",
    name: "Physics Practice Set",
    subject: "Physics",
    category: "practice",
    score: 78,
    totalMarks: 100,
    date: "2024-01-18",
    topics: ["Mechanics", "Thermodynamics"],
    difficulty: "hard",
    timeSpent: 120,
  },
  {
    id: "3",
    name: "Chemistry Sectional",
    subject: "Chemistry",
    category: "sectional",
    score: 92,
    totalMarks: 100,
    date: "2024-01-20",
    topics: ["Organic Chemistry", "Physical Chemistry"],
    difficulty: "medium",
    timeSpent: 90,
  },
  {
    id: "4",
    name: "JEE Main Mock",
    subject: "Mathematics",
    category: "full",
    score: 234,
    totalMarks: 300,
    date: "2024-01-22",
    topics: ["Calculus", "Algebra", "Coordinate Geometry"],
    difficulty: "hard",
    timeSpent: 180,
  },
  {
    id: "5",
    name: "Biology Quick Test",
    subject: "Biology",
    category: "practice",
    score: 45,
    totalMarks: 50,
    date: "2024-01-25",
    topics: ["Plant Biology", "Ecology"],
    difficulty: "easy",
    timeSpent: 45,
  },
]

export const seedSubjects: Subject[] = [
  {
    id: "1",
    name: "Physics",
    color: "#3b82f6",
    icon: "Atom",
    topics: [
      { id: "1", name: "Mechanics", progress: 75, difficulty: "medium", testsCount: 8 },
      { id: "2", name: "Thermodynamics", progress: 60, difficulty: "hard", testsCount: 5 },
      { id: "3", name: "Optics", progress: 85, difficulty: "easy", testsCount: 12 },
      { id: "4", name: "Electromagnetism", progress: 45, difficulty: "hard", testsCount: 6 },
    ],
  },
  {
    id: "2",
    name: "Chemistry",
    color: "#10b981",
    icon: "Flask",
    topics: [
      { id: "5", name: "Organic Chemistry", progress: 80, difficulty: "medium", testsCount: 10 },
      { id: "6", name: "Inorganic Chemistry", progress: 70, difficulty: "medium", testsCount: 8 },
      { id: "7", name: "Physical Chemistry", progress: 55, difficulty: "hard", testsCount: 7 },
    ],
  },
  {
    id: "3",
    name: "Biology",
    color: "#f59e0b",
    icon: "Leaf",
    topics: [
      { id: "8", name: "Cell Biology", progress: 90, difficulty: "easy", testsCount: 15 },
      { id: "9", name: "Genetics", progress: 65, difficulty: "medium", testsCount: 9 },
      { id: "10", name: "Ecology", progress: 75, difficulty: "easy", testsCount: 11 },
      { id: "11", name: "Human Physiology", progress: 50, difficulty: "hard", testsCount: 6 },
    ],
  },
  {
    id: "4",
    name: "Mathematics",
    color: "#dc2626",
    icon: "Calculator",
    topics: [
      { id: "12", name: "Calculus", progress: 85, difficulty: "hard", testsCount: 12 },
      { id: "13", name: "Algebra", progress: 90, difficulty: "medium", testsCount: 14 },
      { id: "14", name: "Coordinate Geometry", progress: 70, difficulty: "medium", testsCount: 10 },
      { id: "15", name: "Trigonometry", progress: 95, difficulty: "easy", testsCount: 16 },
    ],
  },
]

export const seedCalendarEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "NEET Mock Test 2",
    date: "2024-02-01",
    type: "test",
    description: "Full syllabus mock test",
  },
  {
    id: "2",
    title: "Physics Study Session",
    date: "2024-01-30",
    type: "study",
    description: "Focus on Electromagnetism",
  },
  {
    id: "3",
    title: "Chemistry Revision",
    date: "2024-02-03",
    type: "study",
    description: "Organic Chemistry concepts",
  },
  {
    id: "4",
    title: "JEE Main Registration Deadline",
    date: "2024-02-05",
    type: "reminder",
    description: "Last date for JEE Main registration",
  },
]

export const seedAchievements: Achievement[] = [
  {
    id: "1",
    title: "First Steps",
    description: "Complete your first test",
    icon: "Trophy",
    unlockedDate: "2024-01-15",
    progress: 1,
    target: 1,
  },
  {
    id: "2",
    title: "Consistent Performer",
    description: "Complete 10 tests",
    icon: "Target",
    progress: 5,
    target: 10,
  },
  {
    id: "3",
    title: "High Achiever",
    description: "Score above 80% in 5 tests",
    icon: "Star",
    progress: 2,
    target: 5,
  },
  {
    id: "4",
    title: "Subject Master",
    description: "Complete all topics in a subject",
    icon: "BookOpen",
    progress: 0,
    target: 1,
  },
]

export const seedGoals: Goal[] = [
  {
    id: "1",
    title: "Achieve 85% Average Score",
    description: "Maintain an average score of 85% across all tests this month",
    targetValue: 85,
    currentValue: 78,
    unit: "%",
    deadline: "2024-02-29",
    status: "active",
    createdDate: "2024-01-01",
  },
  {
    id: "2",
    title: "Complete 20 Tests",
    description: "Take 20 practice tests before the main exam",
    targetValue: 20,
    currentValue: 5,
    unit: "tests",
    deadline: "2024-03-15",
    status: "active",
    createdDate: "2024-01-01",
  },
  {
    id: "3",
    title: "Master Physics Topics",
    description: "Complete all Physics topics with 90% progress",
    targetValue: 100,
    currentValue: 66,
    unit: "% progress",
    deadline: "2024-02-15",
    status: "active",
    createdDate: "2024-01-10",
  },
]
